const stages=[
{id:'01',emotion:'CURIOSITY',name:'AJAAB',family:'Spiced Amber',sub:'Warm / mysterious',texture:'Dry velvet',mood:'Intrigued',season:'Autumn · Winter',time:'Evening',longevity:'8–10 h',sillage:'Moderate · lingering',top:['Saffron','Bergamot','Pink Pepper'],heart:['Rose','Incense','Nutmeg'],base:['Cold Woods','Amber','Skin Musk'],story:'The unfamiliar room. The door you almost did not open. Ajaab is the scent of discovering something you cannot yet name.',sense:'Cool spice over warm resin, then a quiet woody skin trail.',notfor:'If you want something fresh, obvious or immediately familiar.'},
{id:'02',emotion:'ATTRACTION',name:'UNS',family:'Woody Floral',sub:'Soft / magnetic',texture:'Silk',mood:'Drawn in',season:'All year',time:'Day · Evening',longevity:'7–9 h',sillage:'Moderate',top:['Bergamot','Cardamom','Pink Pepper'],heart:['Jasmine','Iris','Orange Blossom'],base:['Sandalwood','Musk','Amber'],story:'You notice them before you know why. Uns is the quiet pull that turns a passing glance into a second look.',sense:'Clean petals, creamy woods and a warm skin-like finish.',notfor:'If you prefer sharp citrus or aggressively loud projection.'},
{id:'03',emotion:'INTOXICATION',name:'KHUMAAR',family:'Spiced Amber',sub:'Warm / addictive',texture:'Molten',mood:'Consumed',season:'Autumn · Winter',time:'Night',longevity:'9–11 h',sillage:'Strong',top:['Mandarin','Saffron','Pink Pepper'],heart:['Rose','Cinnamon','Jasmine'],base:['Amber','Vanilla','Dark Woods'],story:'The hour when restraint becomes optional. Khumaar is warmth, spice and the feeling of staying longer than you intended.',sense:'Sweet spice opens bright, melts into amber and settles into dark woods.',notfor:'If you want something airy, minimal or purely daytime.'},
{id:'04',emotion:'MYSTERY',name:'ASRAAR',family:'Dark Woods',sub:'Smoky / enigmatic',texture:'Ink',mood:'Unresolved',season:'Autumn · Winter',time:'Evening · Night',longevity:'9–11 h',sillage:'Moderate · dark',top:['Black Pepper','Bergamot','Clove'],heart:['Incense','Rose','Cedar'],base:['Oud Accord','Patchouli','Amber'],story:'Not everything asks to be understood. Asraar lives in the unanswered question, the glance that gives nothing away.',sense:'Pepper and incense move through dry cedar into a shadowy amber base.',notfor:'If you want sweetness to lead the composition.'},
{id:'05',emotion:'DESIRE',name:'TALAB',family:'Woody Floral',sub:'Creamy / yearning',texture:'Warm skin',mood:'Restless',season:'All year',time:'Evening',longevity:'8–10 h',sillage:'Moderate',top:['Bergamot','Pear','Pink Pepper'],heart:['Jasmine','Tuberose','Rose'],base:['Sandalwood','Musk','Vanilla'],story:'Wanting is its own kind of weather. Talab is the scent of reaching, waiting and imagining the moment before it arrives.',sense:'Juicy brightness gives way to creamy florals and soft sandalwood.',notfor:'If you dislike floral warmth or intimate sweetness.'},
{id:'06',emotion:'CLOSENESS',name:'QURBAT',family:'Musk Woody',sub:'Clean / intimate',texture:'Bare skin',mood:'Tender',season:'All year',time:'Day · Evening',longevity:'7–9 h',sillage:'Soft',top:['Neroli','Bergamot','Aldehydic Accord'],heart:['Orange Blossom','Iris','Jasmine'],base:['White Musk','Sandalwood','Cashmere Woods'],story:'Some closeness is almost silent. Qurbat is the warmth of being beside someone without needing to speak.',sense:'Fresh linen-like lightness settling into musk and creamy woods.',notfor:'If you want dramatic projection.'},
{id:'07',emotion:'SEPARATION',name:'FIRAQ',family:'Woody Amber',sub:'Dry / melancholic',texture:'Faded paper',mood:'Longing',season:'Autumn · Winter',time:'Night',longevity:'8–10 h',sillage:'Soft · persistent',top:['Bergamot','Black Pepper','Violet Leaf'],heart:['Iris','Orris','Cedar'],base:['Vetiver','Amber','Musk'],story:'Some distances leave a scent behind. Firaq is what remains when the room is empty but memory refuses to leave.',sense:'Dry iris and cedar with a cool mineral edge and soft amber residue.',notfor:'If you want bright, celebratory sweetness.'},
{id:'08',emotion:'MEMORY',name:'YAAD',family:'Amber Floral',sub:'Powdery / nostalgic',texture:'Old photograph',mood:'Nostalgic',season:'All year',time:'Anytime',longevity:'8–10 h',sillage:'Moderate',top:['Pear','Bergamot','Pink Pepper'],heart:['Rose','Violet','Iris'],base:['Vanilla','Musk','Sandalwood'],story:'Memory never arrives in order. Yaad is a familiar voice, an old room, a shirt that still smells like someone.',sense:'Soft fruit and powdery petals melt into vanilla musk and sandalwood.',notfor:'If you prefer dry, austere compositions.'},
{id:'09',emotion:'LOVE',name:'ISHQ',family:'Floral Amber',sub:'Radiant / sensual',texture:'Warm silk',mood:'Surrendered',season:'All year',time:'Day · Night',longevity:'9–11 h',sillage:'Moderate · radiant',top:['Bergamot','Mandarin','Pink Pepper'],heart:['Rose','Jasmine','Orange Blossom'],base:['Amber','Vanilla','Musk'],story:'At some point the question disappears. Ishq is the quiet certainty after wanting, wondering and waiting.',sense:'Citrus light over luminous florals, ending in warm ambered skin.',notfor:'If you want something deliberately cold or detached.'}
];
const price=299,mrp=399,collectionPrice=2499;
function stage(id){return stages.find(s=>s.id===id)||stages[0]}
function money(n){return '₹'+Number(n).toLocaleString('en-IN')}
function cart(){try{return JSON.parse(localStorage.getItem('whiff-cart')||'[]')}catch{return[]}}
function saveCart(c){localStorage.setItem('whiff-cart',JSON.stringify(c));updateCartCount()}
function updateCartCount(){document.querySelectorAll('[data-cart-count]').forEach(e=>e.textContent=cart().reduce((a,b)=>a+b.qty,0))}
function toast(t){let e=document.querySelector('.toast');if(!e){e=document.createElement('div');e.className='toast';document.body.appendChild(e)}e.textContent=t;e.style.opacity=1;clearTimeout(window.__toast);window.__toast=setTimeout(()=>e.style.opacity=0,1800)}
function addToCart(id){const c=cart(),item=c.find(x=>x.id===id);if(item)item.qty++;else c.push({id,qty:1});saveCart(c);toast(stage(id).name+' added to your stages.');}
function renderStages(target='.stage-list'){const el=document.querySelector(target);if(!el)return;el.innerHTML=stages.map(s=>`<a class="stage-card reveal" href="/stages/${s.id}.html"><span class="stage-num">${s.id} / ${s.emotion}</span><span class="stage-word">${s.name}</span><span><span class="stage-name">${s.family}</span><span class="stage-note">${s.texture} · ${s.mood} · ${s.sillage}</span></span></a>`).join('');reveal()}
function renderJourney(target='.journey'){const el=document.querySelector(target);if(!el)return;el.innerHTML=stages.map(s=>`<a href="/stages/${s.id}.html"><small>${s.id} / ${s.name}</small><span class="jword">${s.emotion}</span></a>`).join('')}
function renderOlfactive(target='.olfactive-index'){const el=document.querySelector(target);if(!el)return;el.innerHTML=stages.map(s=>`<div><span class="mono">${s.id} / ${s.emotion}</span><b>${s.family}</b><span>${s.top[0]} · ${s.heart[0]} · ${s.base[0]}</span></div>`).join('')}
function renderCart(){const el=document.querySelector('#cart-items');if(!el)return;const c=cart();if(!c.length){el.innerHTML='<p class="empty">Nothing here yet. Find the stage that stays with you.</p>';const t=document.querySelector('#cart-total');if(t)t.textContent=money(0);return}let subtotal=0;el.innerHTML=c.map(x=>{const s=stage(x.id),p=price*x.qty;subtotal+=p;return `<div class="cart-row"><div><span class="mono">${s.id} / ${s.emotion}</span><div class="serif" style="font-size:36px">${s.name}</div><small>${s.family} · ${s.texture}</small></div><div class="qty">× ${x.qty}</div><div>${money(p)}<button data-remove="${s.id}" style="display:block;border:0;background:none;padding:8px 0 0;text-decoration:underline;cursor:pointer;font-size:10px">remove</button></div></div>`}).join('');const full=c.length===9&&c.every(x=>x.qty===1);document.querySelector('#cart-total').textContent=money(full?collectionPrice:subtotal);el.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{saveCart(c.filter(x=>x.id!==b.dataset.remove));renderCart()})}
function whatsapp(){const c=cart();if(!c.length){toast('Add a stage first.');return}const full=c.length===9&&c.every(x=>x.qty===1);const subtotal=c.reduce((a,x)=>a+price*x.qty,0);const total=full?collectionPrice:subtotal;const lines=c.map(x=>`${x.id} / ${stage(x.id).name} × ${x.qty}`).join('\n');const msg=`Hello WHIFF, I would like to order:\n\n${lines}\n\n${full?'Full Collection Price: ':'Total: '}${money(total)}\n\nName:\nPhone:\nAddress:`;window.open('https://wa.me/?text='+encodeURIComponent(msg),'_blank')}
function finder(){const questions=document.querySelectorAll('.question');if(!questions.length)return;let answers=[];questions.forEach((q,i)=>q.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>{answers[i]=b.dataset.answer;questions[i].classList.remove('active');if(questions[i+1])questions[i+1].classList.add('active');else showResult()}));function showResult(){let scores=stages.map(s=>({s,n:0}));answers.join(' ').toLowerCase().split(/\s+/).forEach(word=>scores.forEach(x=>{if(x.s.emotion.toLowerCase().includes(word)||x.s.mood.toLowerCase().includes(word)||x.s.texture.toLowerCase().includes(word)||x.s.time.toLowerCase().includes(word))x.n++}));const best=scores.sort((a,b)=>b.n-a.n)[0].s;const r=document.querySelector('.result');if(r){r.innerHTML=`<span class="mono">YOUR STAGE</span><h2>${best.id} / ${best.emotion}</h2><p class="section-copy">${best.name} · ${best.family}. ${best.sense}</p><a class="cta" href="/stages/${best.id}.html">Meet ${best.name}</a>`;r.classList.add('show')}}}
function reveal(){if(matchMedia('(prefers-reduced-motion: reduce)').matches){document.querySelectorAll('.reveal').forEach(e=>e.classList.add('visible'));return}const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');io.unobserve(e.target)}}),{threshold:.08});document.querySelectorAll('.reveal').forEach(e=>io.observe(e))}
document.addEventListener('DOMContentLoaded',()=>{updateCartCount();renderStages();renderJourney();renderOlfactive();renderCart();finder();reveal();document.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>addToCart(b.dataset.add));document.querySelectorAll('[data-whatsapp]').forEach(b=>b.onclick=whatsapp)})
