const stages=[
{id:'01',emotion:'CURIOSITY',name:'AJAAB',family:'Spiced Amber',texture:'Dry velvet',mood:'Intrigued',time:'Evening',top:['Saffron','Bergamot','Pink Pepper'],heart:['Rose','Incense','Nutmeg'],base:['Cold Woods','Amber','Skin Musk'],story:'The unfamiliar room. The door you almost did not open. Ajaab is the scent of discovering something you cannot yet name.',sense:'Cool spice over warm resin, then a quiet woody skin trail.',notfor:'If you want something fresh, obvious or immediately familiar.',visual:'threshold',palette:['#D8D0B8','#16181A','#8E8A76'],keys:['curious','unfamiliar','new','wonder','explore','question','intrigue','warm','spice']},
{id:'02',emotion:'ATTRACTION',name:'UNS',family:'Woody Floral',texture:'Silk',mood:'Drawn in',time:'Day · Evening',top:['Bergamot','Cardamom','Pink Pepper'],heart:['Jasmine','Iris','Orange Blossom'],base:['Sandalwood','Musk','Amber'],story:'You notice them before you know why. Uns is the quiet pull that turns a passing glance into a second look.',sense:'Clean petals, creamy woods and a warm skin-like finish.',notfor:'If you prefer sharp citrus or aggressively loud projection.',visual:'pull',palette:['#D9C6C0','#201A1C','#A9857B'],keys:['drawn','someone','magnetic','romantic','soft','silk','petal','second']},
{id:'03',emotion:'INTOXICATION',name:'KHUMAAR',family:'Spiced Amber',texture:'Molten',mood:'Consumed',time:'Night',top:['Mandarin','Saffron','Pink Pepper'],heart:['Rose','Cinnamon','Jasmine'],base:['Amber','Vanilla','Dark Woods'],story:'The hour when restraint becomes optional. Khumaar is warmth, spice and the feeling of staying longer than you intended.',sense:'Sweet spice opens bright, melts into amber and settles into dark woods.',notfor:'If you want something airy, minimal or purely daytime.',visual:'heat',palette:['#B96D43','#1D1511','#E1A56F'],keys:['danger','obsessed','consumed','addicted','intense','night','warm','sweet','spice']},
{id:'04',emotion:'MYSTERY',name:'ASRAAR',family:'Dark Woods',texture:'Ink',mood:'Unresolved',time:'Evening · Night',top:['Black Pepper','Bergamot','Clove'],heart:['Incense','Rose','Cedar'],base:['Oud Accord','Patchouli','Amber'],story:'Not everything asks to be understood. Asraar lives in the unanswered question, the glance that gives nothing away.',sense:'Pepper and incense move through dry cedar into a shadowy amber base.',notfor:'If you want sweetness to lead the composition.',visual:'shadow',palette:['#1C2631','#EEE9DD','#526A79'],keys:['dark','mysterious','unknown','unresolved','secret','smoke','ink','enigmatic','cool']},
{id:'05',emotion:'DESIRE',name:'TALAB',family:'Woody Floral',texture:'Warm skin',mood:'Restless',time:'Evening',top:['Bergamot','Pear','Pink Pepper'],heart:['Jasmine','Tuberose','Rose'],base:['Sandalwood','Musk','Vanilla'],story:'Wanting is its own kind of weather. Talab is the scent of reaching, waiting and imagining the moment before it arrives.',sense:'Juicy brightness gives way to creamy florals and soft sandalwood.',notfor:'If you dislike floral warmth or intimate sweetness.',visual:'reach',palette:['#C9A8A0','#21191A','#B57C76'],keys:['want','wanting','craving','yearning','restless','desire','wait','imagine','warm','creamy']},
{id:'06',emotion:'CLOSENESS',name:'QURBAT',family:'Musk Woody',texture:'Bare skin',mood:'Tender',time:'Day · Evening',top:['Neroli','Bergamot','Aldehydic Accord'],heart:['Orange Blossom','Iris','Jasmine'],base:['White Musk','Sandalwood','Cashmere Woods'],story:'Some closeness is almost silent. Qurbat is the warmth of being beside someone without needing to speak.',sense:'Fresh linen-like lightness settling into musk and creamy woods.',notfor:'If you want dramatic projection.',visual:'near',palette:['#E7E3D8','#1B2020','#AAB2A7'],keys:['close','tender','intimate','beside','soft','skin','linen','together','quiet']},
{id:'07',emotion:'SEPARATION',name:'FIRAQ',family:'Woody Amber',texture:'Faded paper',mood:'Longing',time:'Night',top:['Bergamot','Black Pepper','Violet Leaf'],heart:['Iris','Orris','Cedar'],base:['Vetiver','Amber','Musk'],story:'Some distances leave a scent behind. Firaq is what remains when the room is empty but memory refuses to leave.',sense:'Dry iris and cedar with a cool mineral edge and soft amber residue.',notfor:'If you want bright, celebratory sweetness.',visual:'distance',palette:['#B9B7AE','#151719','#777970'],keys:['far','distance','apart','missing','absence','longing','loss','alone','cool','dry']},
{id:'08',emotion:'MEMORY',name:'YAAD',family:'Amber Floral',texture:'Old photograph',mood:'Nostalgic',time:'Anytime',top:['Pear','Bergamot','Pink Pepper'],heart:['Rose','Violet','Iris'],base:['Vanilla','Musk','Sandalwood'],story:'Memory never arrives in order. Yaad is a familiar voice, an old room, a shirt that still smells like someone.',sense:'Soft fruit and powdery petals melt into vanilla musk and sandalwood.',notfor:'If you prefer dry, austere compositions.',visual:'echo',palette:['#D7C9B8','#27221D','#9A8572'],keys:['memory','remember','nostalgic','familiar','old','past','photograph','voice','powder']},
{id:'09',emotion:'LOVE',name:'ISHQ',family:'Floral Amber',texture:'Warm silk',mood:'Surrendered',time:'Day · Night',top:['Bergamot','Mandarin','Pink Pepper'],heart:['Rose','Jasmine','Orange Blossom'],base:['Amber','Vanilla','Musk'],story:'At some point the question disappears. Ishq is the quiet certainty after wanting, wondering and waiting.',sense:'Citrus light over luminous florals, ending in warm ambered skin.',notfor:'If you want something deliberately cold or detached.',visual:'bloom',palette:['#D8B8B4','#221719','#C88478'],keys:['love','surrender','certainty','radiant','alive','together','heart','sensual','warm','light']}
];
const price=299,mrp=399,collectionPrice=2499,discoveryPrice=499;
const articles=[
['01','ESSAY','08','04 MIN','why-do-some-scents-feel-like-people','Why do some scents feel like people?','Memory, association and the strange architecture of recognition.',`There are smells that belong to no object anymore. A shirt, a room, a person can disappear and somehow the scent survives.|The brain does not store fragrance like a neat list of ingredients. It stores it alongside place, emotion, time and the people who happened to be there. That is why a familiar drydown can feel less like smelling something and more like opening a door.|This is the peculiar power of perfume. It does not simply announce who we are. It can return us to who we were, sometimes before we are ready.`],
['02','ESSAY','01','05 MIN','the-art-of-the-drydown','The art of the drydown.','Why the first spray is never the whole story.',`A perfume begins loudly. Citrus flashes. Spice rises. Flowers arrive. For a few minutes, the composition is introducing itself.|Then the architecture settles. The volatile notes recede, the heart becomes clearer and the materials with greater staying power begin to shape the skin. This is the drydown, the part of the perfume that asks you to stay.|At WHIFF, the first impression is only one part of the story. The character is what happens after the room has stopped noticing the opening.`],
['03','ESSAY','ALL','03 MIN','there-is-no-correct-stage','There is no correct stage.','A fragrance is not a personality test. It is a conversation.',`You do not have to be one feeling. You do not have to wear the same fragrance because it sounds like you on paper.|A stage can be temporary. Curiosity in the morning. Desire at night. Memory on an ordinary Tuesday. The point is not to choose a permanent identity.|The point is to notice where you are, and sometimes where you want to go.`],
['04','FIELD NOTES','07','03 MIN','the-room-after-someone-leaves','The room after someone leaves.','A field note on absence, skin and the persistence of a trace.',`The strangest part of an empty room is that it is rarely empty. A chair keeps its shape. A glass keeps a fingerprint. The air keeps something for a little longer.|Firaq was built around that interval. Not grief as spectacle, but absence as atmosphere. Dry iris, cedar and amber are given enough space to feel like a trace rather than an announcement.`],
['05','SCIENCE OF SCENT','01','06 MIN','why-the-same-perfume-smells-different','Why the same perfume smells different on different skin.','Skin chemistry, temperature and the moving surface beneath a fragrance.',`Perfume is not a fixed picture. It is a moving mixture interacting with heat, moisture, oils and the environment around the wearer.|That is why a composition can feel brighter on one person and warmer on another. Temperature can accelerate evaporation. Skin oils can soften or extend certain materials. Even humidity changes the way a trail travels through a room.|There is no single correct version of a fragrance. The wearer becomes part of the composition.`],
['06','STAGE STORY','03','04 MIN','staying-longer-than-you-intended','Staying longer than you intended.','Khumaar and the hour when restraint becomes optional.',`There is a particular kind of night that starts without a plan. One drink becomes another hour. A conversation stretches. Nobody announces the decision to stay.|Khumaar belongs there. Sweet spice, rose, amber and dark woods create the feeling of warmth gathering around you until leaving feels strangely premature.`]
];
function stage(id){return stages.find(s=>s.id===String(id))||stages[0]}
function money(n){return '₹'+Number(n).toLocaleString('en-IN')}
function cart(){try{return JSON.parse(localStorage.getItem('whiff-cart')||'[]')}catch{return[]}}
function saveCart(c){localStorage.setItem('whiff-cart',JSON.stringify(c));updateCartCount()}
function updateCartCount(){document.querySelectorAll('[data-cart-count]').forEach(e=>e.textContent=cart().reduce((a,b)=>a+b.qty,0))}
function toast(t){let e=document.querySelector('.toast');if(!e){e=document.createElement('div');e.className='toast';document.body.appendChild(e)}e.textContent=t;e.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>e.classList.remove('show'),1800)}
function addToCart(id){const c=cart(),i=c.find(x=>x.id===String(id));i?i.qty++:c.push({id:String(id),qty:1});saveCart(c);toast(stage(id).name+' added.');renderCart()}
function addCollection(){saveCart(stages.map(s=>({id:s.id,qty:1})));toast('Collection 01 added · ₹2,499.');renderCart()}
function renderStages(){const e=document.querySelector('.stage-list');if(!e)return;e.innerHTML=stages.map(s=>`<a class="stage-card world-${s.visual} reveal" href="/stages/${s.id}.html"><span class="stage-num">${s.id} / ${s.emotion}</span><span class="stage-symbol">${s.id}</span><span class="stage-word">${s.name}</span><span><span class="stage-name">${s.family}</span><span class="stage-note">${s.texture} · ${s.mood}</span></span></a>`).join('');reveal()}
function renderJourney(){const e=document.querySelector('.journey');if(!e)return;e.innerHTML=stages.map(s=>`<a class="journey-${s.id}" href="/stages/${s.id}.html"><small>${s.id} / ${s.name}</small><span class="jword">${s.emotion}</span></a>`).join('')}
function renderOlfactive(){const e=document.querySelector('.olfactive-index');if(!e)return;e.innerHTML=stages.map(s=>`<a href="/stages/${s.id}.html"><span class="mono">${s.id} / ${s.emotion}</span><b>${s.family}</b><span>${s.top[0]} · ${s.heart[0]} · ${s.base[0]}</span></a>`).join('')}
function renderJournal(){const e=document.querySelector('[data-journal-grid]');if(!e)return;e.innerHTML=articles.map(a=>`<a class="article reveal" href="/journal/${a[4]}.html"><span class="mono">${a[1]} / ${a[0]} · ${a[3]} · ${a[2]==='ALL'?'ALL STAGES':'STAGE '+a[2]}</span><h2>${a[5]}</h2><p>${a[6]}</p><span class="read-link">READ ARTICLE ↗</span></a>`).join('');reveal()}
function renderArticle(){const e=document.querySelector('[data-article-content]'),slug=document.body.dataset.article;if(!e||!slug)return;const a=articles.find(x=>x[4]===slug);if(!a)return;document.title=a[5]+' | The WHIFF Journal';e.innerHTML=`<header class="article-header"><span class="mono">${a[1]} / ${a[0]} · ${a[3]} · ${a[2]==='ALL'?'ALL STAGES':'STAGE '+a[2]}</span><h1>${a[5]}</h1><p>${a[6]}</p></header><div class="article-body">${a[7].split('|').map((p,i)=>`<p class="${i===1?'article-lead':''}">${p}</p>`).join('')}</div><div class="article-end"><span class="mono">THE WHIFF JOURNAL</span><a class="cta" href="/journal.html">Back to Journal</a></div>`}
function renderCart(){const e=document.querySelector('#cart-items');if(!e)return;const c=cart(),totalEl=document.querySelector('#cart-total');if(!c.length){e.innerHTML='<div class="empty-cart"><span class="mono">YOUR COLLECTION / 00</span><p>Nothing here yet.<br>Find the stage that stays with you.</p><a class="cta" href="/collection.html">Explore Stages</a></div>';if(totalEl)totalEl.textContent=money(0);return}const full=c.length===9&&c.every(x=>x.qty===1),total=full?collectionPrice:c.reduce((a,x)=>a+price*x.qty,0);e.innerHTML=c.map(x=>{const s=stage(x.id);return `<div class="cart-row"><div><span class="mono">${s.id} / ${s.emotion}</span><div class="cart-name serif">${s.name}</div><small>${s.family} · ${s.texture}</small></div><div class="qty-control"><button data-minus="${s.id}">−</button><span>${x.qty}</span><button data-plus="${s.id}">+</button></div><div class="cart-price">${money(price*x.qty)}<button data-remove="${s.id}">Remove</button></div></div>`}).join('');if(totalEl)totalEl.textContent=money(total);e.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{saveCart(c.filter(x=>x.id!==b.dataset.remove));renderCart()});e.querySelectorAll('[data-minus]').forEach(b=>b.onclick=()=>changeQty(b.dataset.minus,-1));e.querySelectorAll('[data-plus]').forEach(b=>b.onclick=()=>changeQty(b.dataset.plus,1))}
function changeQty(id,d){const c=cart(),i=c.find(x=>x.id===id);if(!i)return;i.qty+=d;i.qty<1?saveCart(c.filter(x=>x.id!==id)):saveCart(c);renderCart()}
function whatsapp(){const c=cart();if(!c.length){toast('Add a stage first.');return}const full=c.length===9&&c.every(x=>x.qty===1),total=full?collectionPrice:c.reduce((a,x)=>a+price*x.qty,0),lines=c.map(x=>`${x.id} / ${stage(x.id).name} × ${x.qty}`).join('\n'),msg=`Hello WHIFF, I would like to order:\n\n${lines}\n\n${full?'Collection 01: ':'Total: '}${money(total)}\n\nName:\nPhone:\nAddress:`;window.open('https://wa.me/?text='+encodeURIComponent(msg),'_blank')}
function finder(){const root=document.querySelector('[data-finder]');if(!root)return;const qs=[...root.querySelectorAll('.finder-question')],answers=[];function go(i){qs[i].classList.remove('active');if(qs[i+1]){qs[i+1].classList.add('active');root.querySelector('.finder-progress').style.width=((i+2)/qs.length*100)+'%'}else result()}qs.forEach((q,i)=>q.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>{answers[i]={stage:b.dataset.stage||'',weights:(b.dataset.weights||'').split(',').filter(Boolean)};go(i)}));root.querySelectorAll('[data-finder-back]').forEach(b=>b.onclick=()=>{const i=qs.findIndex(q=>q.classList.contains('active'));if(i>0){qs[i].classList.remove('active');qs[i-1].classList.add('active');answers.pop();root.querySelector('.finder-progress').style.width=(i/qs.length*100)+'%'}});function result(){const scored=stages.map(s=>({s,n:0}));answers.forEach(a=>scored.forEach(x=>{if(a.stage===x.s.id)x.n+=7;a.weights.forEach(w=>{if(x.s.keys.includes(w))x.n+=2})}));scored.sort((a,b)=>b.n-a.n);const best=scored[0].s,alt=scored[1].s,r=root.querySelector('.finder-result');r.innerHTML=`<span class="mono">YOUR STAGE</span><div class="result-number">${best.id}</div><div class="result-emotion">${best.emotion}</div><h2>${best.name}</h2><p>${best.story}</p><div class="result-pair"><span>Also consider</span><a href="/stages/${alt.id}.html">${alt.id} / ${alt.emotion}</a></div><a class="cta" href="/stages/${best.id}.html">Meet ${best.name}</a><button class="text-button" data-reset>Start again</button>`;qs.forEach(q=>q.classList.remove('active'));r.classList.add('show');r.querySelector('[data-reset]').onclick=()=>{answers.length=0;r.classList.remove('show');qs[0].classList.add('active');root.querySelector('.finder-progress').style.width='25%'}}}
function setStageWorld(){const m=location.pathname.match(/\/stages\/(0[1-9])\.html/);if(!m)return;const s=stage(m[1]);document.body.dataset.stage=s.id;document.documentElement.style.setProperty('--stage-a',s.palette[0]);document.documentElement.style.setProperty('--stage-b',s.palette[1]);document.documentElement.style.setProperty('--stage-c',s.palette[2]);const h=document.querySelector('.stage-hero');if(h&&!h.querySelector('.stage-world')){const v=document.createElement('div');v.className='stage-world visual-'+s.visual;v.innerHTML=`<span>${s.id}</span><i></i><b></b>`;h.prepend(v)}}
function reveal(){if(matchMedia('(prefers-reduced-motion: reduce)').matches){document.querySelectorAll('.reveal').forEach(e=>e.classList.add('visible'));return}const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');io.unobserve(e.target)}}),{threshold:.05});document.querySelectorAll('.reveal').forEach(e=>io.observe(e))}
document.addEventListener('DOMContentLoaded',()=>{setStageWorld();updateCartCount();renderStages();renderJourney();renderOlfactive();renderJournal();renderArticle();renderCart();finder();reveal();document.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>addToCart(b.dataset.add));document.querySelectorAll('[data-add-collection]').forEach(b=>b.onclick=addCollection);document.querySelectorAll('[data-whatsapp]').forEach(b=>b.onclick=whatsapp)});