(function(){
  const root=document.documentElement;
  const esc=s=>String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
  if(!document.querySelector('link[data-whiff-visual]')){const l=document.createElement('link');l.rel='stylesheet';l.href='/whiff-visual.css';l.dataset.whiffVisual='1';document.head.appendChild(l)}
  function bottleSVG(s,small){const name=esc(s?.name||'WHIFF'),id=esc(s?.id||'01'),liquid=s?.palette?.[2]||'#b08a55',uid='w'+Math.random().toString(36).slice(2,9);return `<div class="whiff-bottle ${small?'is-small':'is-large'} bottle-float" aria-hidden="true"><svg viewBox="0 0 260 430"><defs><linearGradient id="${uid}g" x1="0" x2="1"><stop stop-color="#fff" stop-opacity=".48"/><stop offset=".18" stop-color="#fff" stop-opacity=".08"/><stop offset=".48" stop-color="#fff" stop-opacity=".3"/><stop offset=".78" stop-color="#fff" stop-opacity=".06"/><stop offset="1" stop-color="#fff" stop-opacity=".5"/></linearGradient><linearGradient id="${uid}l" x1="0" y1="0" x2="0" y2="1"><stop stop-color="${liquid}" stop-opacity=".36"/><stop offset="1" stop-color="${liquid}" stop-opacity=".82"/></linearGradient><linearGradient id="${uid}c" x1="0" x2="1"><stop stop-color="#050505"/><stop offset=".45" stop-color="#222"/><stop offset=".72" stop-color="#090909"/><stop offset="1" stop-color="#2b2b2b"/></linearGradient></defs><ellipse cx="130" cy="405" rx="80" ry="13" fill="#000" opacity=".28"/><g><rect x="91" y="28" width="78" height="75" rx="8" fill="url(#${uid}c)"/><rect x="99" y="95" width="62" height="12" rx="3" fill="#bfc0be" opacity=".65"/><path d="M82 103h96v23c0 9 7 16 16 20 14 7 22 21 22 38v185c0 18-14 32-32 32H76c-18 0-32-14-32-32V184c0-17 8-31 22-38 9-4 16-11 16-20z" fill="url(#${uid}g)" stroke="#fff" stroke-opacity=".6" stroke-width="2"/><path d="M47 274h166v95c0 14-11 25-25 25H72c-14 0-25-11-25-25z" fill="url(#${uid}l)"/><path d="M48 273c34 7 128 7 164 0" fill="none" stroke="#fff" stroke-opacity=".45" stroke-width="2"/><path d="M72 158c-10 27-11 150-2 211" fill="none" stroke="#fff" stroke-opacity=".58" stroke-width="5" stroke-linecap="round"/><path d="M187 160c10 37 10 120 2 196" fill="none" stroke="#fff" stroke-opacity=".2" stroke-width="3"/><path d="M130 107v167" stroke="#dfe3e1" stroke-opacity=".7" stroke-width="2"/><rect x="68" y="211" width="124" height="82" rx="2" fill="#f5f1e7" fill-opacity=".91" stroke="#111" stroke-opacity=".13"/><text x="130" y="230" text-anchor="middle" font-size="7" fill="#171717" letter-spacing="1.2">WHIFF / COLLECTION 01</text><text x="130" y="263" text-anchor="middle" font-size="31" fill="#171717" font-family="Georgia,serif">${name}</text><text x="130" y="277" text-anchor="middle" font-size="6" fill="#171717" letter-spacing="1">${id} · EAU DE PARFUM · 30 ML</text></g></svg></div>`}
  function kind(note){const n=String(note||'').toLowerCase();if(/bergamot|lemon|mandarin|pear|neroli|orange/.test(n))return'citrus';if(/rose|jasmine|iris|violet|tuberose|blossom|orris/.test(n))return'petal';if(/saffron|pepper|cardamom|cinnamon|clove|nutmeg/.test(n))return'spice';if(/cedar|wood|vetiver|patchouli|oud/.test(n))return'wood';if(/incense|amber|vanilla|musk|cashmere|aldehydic/.test(n))return'threads';return'dot'}
  function strip(s){const ns=[...s.top.slice(0,2),...s.heart.slice(0,2),...s.base.slice(0,2)];return `<div class="whiff-ingredient-strip">${ns.map((n,i)=>`<div class="whiff-ingredient-chip" style="color:${s.palette[(i+1)%s.palette.length]}"><i class="whiff-ingredient ${kind(n)}"></i><span>${esc(n)}</span></div>`).join('')}</div>`}
  function home(){const v=document.querySelector('.hero-visual');if(!v||v.querySelector('.whiff-home-bottle')||!window.stage)return;const s=window.stage('01');v.insertAdjacentHTML('afterbegin',`<div class="whiff-home-bottle">${bottleSVG(s,false)}</div><div class="whiff-hero-label">01 / CURIOSITY<br>AJAAB · SPICED AMBER<br>30 ML EAU DE PARFUM</div>`)}
  function stageWorld(){const page=document.querySelector('[data-stage-page]'),art=document.querySelector('.stage-world');if(!page||!art||!window.stage)return;const s=window.stage(page.dataset.stage);root.style.setProperty('--stage-a',s.palette[0]);root.style.setProperty('--stage-b',s.palette[1]);root.style.setProperty('--stage-c',s.palette[2]);art.classList.add('whiff-stage-art');art.innerHTML=`<span class="whiff-stage-index">${s.id} / ${esc(s.emotion)}</span><i class="whiff-ingredient ing-1 ${kind(s.top[0])}"></i><i class="whiff-ingredient ing-2 ${kind(s.heart[0])}"></i><i class="whiff-ingredient ing-3 ${kind(s.base[0])}"></i>${bottleSVG(s,true)}<span class="whiff-stage-name">${esc(s.name)}.</span>`;const notes=page.querySelector('[data-notes]');if(notes&&!page.querySelector('.whiff-ingredient-strip'))notes.insertAdjacentHTML('afterend',strip(s))}
  function discovery(){document.querySelectorAll('.discovery-art').forEach(el=>{if(el.querySelector('.whiff-box')||!window.stage)return;el.classList.add('whiff-packaging');el.innerHTML=`<div class="whiff-box"><div class="box-face"><span class="box-meta">WHIFF / COLLECTION 01</span><span class="box-title">THE<br>STAGES.</span><span class="box-meta">09 ENCOUNTERS · 01 JOURNEY · 30 ML EDP</span><i class="box-orbit"></i><div class="box-samples">${Array.from({length:9},(_,i)=>`<i style="height:${45+(i%4)*12}%"></i>`).join('')}</div></div><div class="box-face box-top"><span class="box-meta">NINE SMALL ENCOUNTERS</span></div><div class="box-face box-side"><span class="box-meta">FIND THE STAGE THAT STAYS WITH YOU.</span></div></div>`})}
  function collection(){document.querySelectorAll('.discovery-card').forEach(el=>{if(el.querySelector('.whiff-ingredient-strip')||!window.stage)return;el.insertAdjacentHTML('beforeend',strip(window.stage('01')))})}
  function finder(){const result=document.querySelector('.finder-result');if(!result)return;const observer=new MutationObserver(()=>{if(result.querySelector('.whiff-bottle'))return;const id=(result.querySelector('.result-number')?.textContent||'01').trim();const s=window.stage?.(id);if(!s)return;const host=document.createElement('div');host.innerHTML=bottleSVG(s,true);result.insertBefore(host.firstElementChild,result.firstChild)});observer.observe(result,{childList:true,subtree:true})}
  function run(){home();stageWorld();discovery();collection();finder()}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',run,{once:true});else run();
})();
